### ISSUE TITLE
Gulp Build non funziona

### ISSUE THREAD

**Issue by alessandrocataldi** [alessandrocataldi/bueno#14]
# Il problema
Quando lancio il comando `gulp build` nel terminale mi ritorna questo e non finisce di fare il build.
Dare un occhiata qui:

```
events.js:183
      throw er; // Unhandled 'error' event
      ^
GulpUglifyError: unable to minify JavaScript
    at createError (/Users/Alessandro/Documents/GitHub/bueno/node_modules/gulp-uglify/lib/create-error.js:6:14)
    at apply (/Users/Alessandro/Documents/GitHub/bueno/node_modules/gulp-uglify/node_modules/lodash/_apply.js:16:25)
    at wrapper (/Users/Alessandro/Documents/GitHub/bueno/node_modules/gulp-uglify/node_modules/lodash/_createCurry.js:41:12)
    at /Users/Alessandro/Documents/GitHub/bueno/node_modules/gulp-uglify/lib/minify.js:54:15
    at DestroyableTransform._transform (/Users/Alessandro/Documents/GitHub/bueno/node_modules/gulp-uglify/composer.js:10:23)
    at DestroyableTransform.Transform._read (/Users/Alessandro/Documents/GitHub/bueno/node_modules/readable-stream/lib/_stream_transform.js:182:10)
    at DestroyableTransform.Transform._write (/Users/Alessandro/Documents/GitHub/bueno/node_modules/readable-stream/lib/_stream_transform.js:170:83)
    at doWrite (/Users/Alessandro/Documents/GitHub/bueno/node_modules/readable-stream/lib/_stream_writable.js:406:64)
    at writeOrBuffer (/Users/Alessandro/Documents/GitHub/bueno/node_modules/readable-stream/lib/_stream_writable.js:395:5)
    at DestroyableTransform.Writable.write (/Users/Alessandro/Documents/GitHub/bueno/node_modules/readable-stream/lib/_stream_writable.js:322:11)
```

### Le dipendenze installate sono:

```javascript
    "devDependencies": {
    "browser-sync": "^2.18.13",
    "del": "^3.0.0",
    "gulp": "^3.9.1",
    "gulp-cache": "^1.0.1",
    "gulp-imagemin": "^4.0.0",
    "gulp-sass": "^3.1.0",
    "gulp-uglify": "^3.0.0",
    "gulp-useref": "^3.1.3",
    "run-sequence": "^2.2.0"
  },
  "dependencies": {
    "gulp-cssnano": "^2.1.2"
  }
```

### La configurazione di `gulpfile.js` è questa:

```javascript
var gulp = require('gulp');
var sass = require('gulp-sass');
var browserSync = require('browser-sync');
var useref = require('gulp-useref');
var uglify = require('gulp-uglify');
var gulpIf = require('gulp-if');
var cssnano = require('gulp-cssnano');
var imagemin = require('gulp-imagemin');
var cache = require('gulp-cache');
var del = require('del');
var runSequence = require('run-sequence');

// Development Tasks
// -----------------

// Start browserSync server
gulp.task('browserSync', function() {
  browserSync({
    server: {
      baseDir: 'build'
    }
  })
})

gulp.task('sass', function() {
  return gulp.src('build/scss/**/*.scss')
    .pipe(sass().on('error', sass.logError))
    .pipe(gulp.dest('build/css'))
    .pipe(browserSync.reload({
      stream: true
    }));
})

// Watchers
gulp.task('watch', function() {
  gulp.watch('build/scss/**/*.scss', ['sass']);
  gulp.watch('build/*.html', browserSync.reload);
  gulp.watch('build/js/**/*.js', browserSync.reload);
})

// Optimization Tasks
// ------------------

// Optimizing CSS and JavaScript
gulp.task('useref', function() {
  return gulp.src('build/*.html')
    .pipe(useref())
    .pipe(gulpIf('*.js', uglify()))
    .pipe(gulpIf('*.css', cssnano()))
    .pipe(gulp.dest('dist'));
});

// Optimizing Images
gulp.task('images', function() {
  return gulp.src('build/assets/images/**/*.+(png|jpg|jpeg|gif|svg)')
    .pipe(cache(imagemin({
      interlaced: true,
    })))
    .pipe(gulp.dest('dist/images'))
});

// Copying fonts
gulp.task('fonts', function() {
  return gulp.src('build/assets/fonts/**/*')
    .pipe(gulp.dest('dist/fonts'))
})

// Cleaning
gulp.task('clean', function() {
  return del.sync('dist').then(function(cb) {
    return cache.clearAll(cb);
  });
})

gulp.task('clean:dist', function() {
  return del.sync(['dist/**/*', '!dist/images', '!dist/images/**/*']);
});

// Build Sequences
// ---------------

gulp.task('default', function(callback) {
  runSequence(['sass', 'browserSync'], 'watch',
    callback
  )
})

gulp.task('build', function(callback) {
  runSequence(
    'clean:dist',
    'sass',
    ['useref', 'images', 'fonts'],
    callback
  )
})
```
### Il contenuto del file JavaScript che non viene compilato:

```javascript
document.addEventListener('DOMContentLoaded', ()=>{
  console.log("--------------------------------- \n    BUENO STARTING POINT.Js  \n---------------------------------");
  var inputs=document.querySelectorAll("input");
      for  (var input of inputs){
          input.addEventListener("keyup",(e)=>{
              var i=0;
              while (i<e.target.attributes.length) {
                  var attribute = e.target.attributes[i];
                  attribute.name=attribute.name+"";
                  if(attribute.value)
                      attribute.value=attribute.value+"";
                  if(typeof window[attribute.name]==="function"){
                      window[attribute.name](attribute.value,e.target);
                  }
                  i++;
              }
          });
      }
});
required=(noValue,element)=>{
  if(element.value=="")
      error(element,"required");
  else
      success(element);
}
type=(param,element)=>{
  if(param=="email"){
      var emailPattern=/^[a-zA-Z0-9._-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}$/;
      if(emailPattern.test(element.value)){
          success(element);
      }else{
          error(element,"pattern");
      }
  }
}
minlength=(minLength,element)=>{
  if (element.value.length<minLength)
      error(element,"minLength");
  else
      success(element);
}
maxlength=(maxLength,element)=>{
  if (element.value.length<=maxLength)
      success(element);
  else
      error(element,"maxLength");
}
success=(element)=>{
  console.log("success");
  element.classList.remove("alert")
  element.classList.add("success");
}
error=(element,type)=>{
  console.log("error ------"+ type);
  element.classList.remove("success")
  element.classList.add("alert")
}
```

**Comment by andreazanti** [comment]
prima 
gulp.task('useref', function() {
  return gulp.src('build/*.html')
    .pipe(useref())
    .pipe(gulpIf('*.js', uglify()))
    .pipe(gulpIf('*.css', cssnano()))
    .pipe(gulp.dest('dist'));
});

dopo 
gulp.task('useref', function() {
  return gulp.src('build/*.html')
    .pipe(useref())
    .pipe(gulpIf('build/*.js', uglify()))
    .pipe(gulpIf('build/*.css', cssnano()))
    .pipe(gulp.dest('dist'));
});

**Comment by alessandrocataldi** [comment]
Però ora non comprime il file js
